In [3]:
import numpy as np

# 文件读取

In [4]:
ndarray = np.genfromtxt("../data/test.txt", delimiter=',', dtype=str)
print(ndarray)
print(ndarray.dtype)
print(ndarray.shape)

[['name' 'age' 'year']
 ['root' '18' '2001']
 ['tian' '19' '2000']
 ['yun' '20' '2022']]
<U4
(4, 3)


# 构造向量

In [10]:
vectorX = np.array([5, 5, 5, 5])
print(vectorX)
print(vectorX.dtype)
print(vectorX.shape)

[5 5 5 5]
int32
(4,)


# 重构(reshape和flatten)

In [11]:
vector_reshape01 = vectorX.reshape([4, -1])
print(vector_reshape01)
print(vector_reshape01.shape)
print(vector_reshape01.flatten())

[[5]
 [5]
 [5]
 [5]]
(4, 1)
[5 5 5 5]


In [12]:
vector_reshape02 = vectorX.reshape([1, -1])
print(vector_reshape02)
print(vector_reshape02.shape)
print(vector_reshape02.flatten())

[[5 5 5 5]]
(1, 4)
[5 5 5 5]


# 构造矩阵(row * column)

In [13]:
matrix = np.array([[1, 1, 1], [2, 2, 2]])
print(matrix)
print(matrix.dtype)
print(matrix.shape)

[[1 1 1]
 [2 2 2]]
int32
(2, 3)


In [14]:
vector_reshape02 = vectorX.reshape([1, -1])
print(vector_reshape02)
print(vector_reshape02.shape)
print(vector_reshape02.flatten())

[[5 5 5 5]]
(1, 4)
[5 5 5 5]


In [15]:
matrix = np.array([[1, 1, 1], [2, 2, 2]])
print(matrix)
print(matrix.dtype)
print(matrix.shape)

[[1 1 1]
 [2 2 2]]
int32
(2, 3)


In [16]:
matrix = np.array([[1, 1, 1], [2, 2, 2]])
print(matrix)
print(matrix.dtype)
print(matrix.shape)

[[1 1 1]
 [2 2 2]]
int32
(2, 3)


In [17]:
matrix = np.array([[1, 1, 1], [2, 2, 2]])
print(matrix)
print(matrix.dtype)
print(matrix.shape)

[[1 1 1]
 [2 2 2]]
int32
(2, 3)


# 生成特殊矩阵

In [18]:
ones = np.array([1] * 5)
print(ones)


[1 1 1 1 1]


In [20]:
# 与上面的效果相同
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.diag

<function numpy.diag(v, k=0)>

对角矩阵, 需要提供主对角线上的元素列表

In [24]:
np.diag([1, 2, 3, 4, 5, 6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

根据上下限和步长生成矩阵

In [25]:
np.arange(1, 2 * np.pi, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2])

根据上下限和个数等间隔生成矩阵

In [26]:
np.linspace(1, 2 * np.pi, 100)

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904

生成(0, 1)范围内的随机矩阵

In [27]:
np.random.random([3, 4])


array([[0.11664293, 0.86900466, 0.35541249, 0.79839626],
       [0.24076521, 0.22729881, 0.81694713, 0.86151542],
       [0.73555542, 0.99012675, 0.15000602, 0.15116863]])