In [9]:
import numpy as np

# 广播运算

对矩阵中的每一个元素都进行相同的操作

In [10]:
vector = np.array([1, 2, 3, 1, 2, 3])
vector == 2

array([False,  True, False, False,  True, False])

In [11]:
array = np.array([1, 2, 3, 2, 2, 3]).reshape([-1, 2])
array == 2

array([[False,  True],
       [False,  True],
       [ True, False]])

In [12]:
array[array == 2]

array([2, 2, 2])

# 布尔索引

传入一个True和False的列表, 可以根据True的索引值作为筛选条件

**案例1: 挑选出第1列值为2的那些数据**

In [13]:
condition01 = (array[:, 1] == 2)
condition01

array([ True,  True, False])

In [14]:
array[condition01]

array([[1, 2],
       [3, 2]])

# 布尔运算

+ `*`或者`&`代表and
+ `+`或者`|`代表or

In [15]:
conditionX = np.array([True, True, False, False])
conditionY = np.array([True, False, True, False])
print(conditionX * conditionY)
print(conditionX + conditionY)
print(conditionX & conditionY)
print(conditionX | conditionY)

[ True False False False]
[ True  True  True False]
[ True False False False]
[ True  True  True False]


**案例2: 挑选出第1列值为2, 第0列值为1的那些数据**

In [16]:
condition02 = (array[:, 0] == 1)
array[condition01 & condition02]

array([[1, 2]])

# 类型转换

In [17]:
sVector = np.array(["1", "2", "3", "4"])
sVector

array(['1', '2', '3', '4'], dtype='<U1')

In [18]:
sVector = sVector.astype(float)
sVector

array([1., 2., 3., 4.])

# 行(列)的聚合操作
**axis的计算规则**:
+ axis=0: 去掉最外层括号后, 对原本属于同一括号的元素对应聚合
+ axis=1: 去掉次外层括号后, 对原本属于同一括号的元素对应聚合

axis=0的情况
```
[
    [[1,2,3],[4,5,6],[7,8,9]],      [[1,2,3],[4,5,6],[7,8,9]],
    +                               +
    [[2,3,4],[5,6,7],[8,9,0]], ===> [[2,3,4],[5,6,7],[8,9,0]], ===> [[5,8,11],[14,17,20],[23,26,9]]
    +                               +
    [[2,3,4],[5,6,7],[8,9,0]]       [[2,3,4],[5,6,7],[8,9,0]]
]
```

axis=1的情况

```
[                                     [                                 [
    [[1,2,3] + [4,5,6] + [7,8,9]],      [1,2,3] + [4,5,6] + [7,8,9],      [12,15,18],
    [[2,3,4] + [5,6,7] + [8,9,0]], ===> [2,3,4] + [5,6,7] + [8,9,0], ===> [15,18,11],
    [[2,3,4] + [5,6,7] + [8,9,0]]       [2,3,4] + [5,6,7] + [8,9,0]       [15,18,11]
]                                     ]                                 ]
```

axis=2的情况

```
[                                               [                                        [
    [[1 + 2 + 3], [4 + 5 + 6], [7 + 8 + 9]],      [1 + 2 + 3, 4 + 5 + 6, 7 + 8 + 9],       [6,15,24],
    [[2 + 3 + 4], [5 + 6 + 7], [8 + 9 + 0]], ===> [2 + 3 + 4, 5 + 6 + 7, 8 + 9 + 0], ===>  [9,18,17],
    [[2 + 3 + 4], [5 + 6 + 7], [8 + 9 + 0]]       [2 + 3 + 4, 5 + 6 + 7, 8 + 9 + 0]        [9,18,17]
]                                               ]                                        ]
```

In [19]:
matrix = np.arange(1, 10).reshape([3, -1])
print(matrix)
print("*******************")
print(matrix.sum(axis=0))
print("*******************")
print(matrix.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*******************
[12 15 18]
*******************
[ 6 15 24]


In [20]:
tensor = np.arange(1, 28).reshape([3, 3, -1])
print(tensor)
print("*******************")
print(tensor.sum(axis=0))
print("*******************")
print(tensor.sum(axis=1))
print("*******************")
print(tensor.sum(axis=2))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
*******************
[[30 33 36]
 [39 42 45]
 [48 51 54]]
*******************
[[12 15 18]
 [39 42 45]
 [66 69 72]]
*******************
[[ 6 15 24]
 [33 42 51]
 [60 69 78]]
