In [1]:
import numpy as np


In [4]:
matrixA = np.linspace(1, 9, 9).reshape([3, -1])
matrixB = np.linspace(1, 9, 9).reshape([3, -1])
print(matrixA)
print(matrixB)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 矩阵基本运算

## 乘法

In [5]:
np.dot(matrixA, matrixB)

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

In [7]:
randomMatrix = np.random.random([3, 4]) * 10
np.floor(randomMatrix)

array([[9., 3., 7., 8.],
       [6., 5., 1., 1.],
       [8., 9., 5., 1.]])

In [8]:
randomMatrix.flatten()


array([9.52060906, 3.3690725 , 7.77365556, 8.92102856, 6.30892887,
       5.10728605, 1.58188717, 1.91144788, 8.54638819, 9.98650626,
       5.23610422, 1.71781273])

In [9]:
randomMatrix.ravel()

array([9.52060906, 3.3690725 , 7.77365556, 8.92102856, 6.30892887,
       5.10728605, 1.58188717, 1.91144788, 8.54638819, 9.98650626,
       5.23610422, 1.71781273])

## 转置

In [25]:
randomMatrix.T

array([[9.52060906, 6.30892887, 8.54638819],
       [3.3690725 , 5.10728605, 9.98650626],
       [7.77365556, 1.58188717, 5.23610422],
       [8.92102856, 1.91144788, 1.71781273]])

## 复制

In [27]:
vectorX = np.linspace(1, 3, 3)
# 深拷贝
vectorY = vectorX.copy()
# 浅拷贝
vectorZ = vectorX
print(vectorX)
print(vectorY)
print(vectorZ)

vectorX[0] = 2
print(vectorX)
print(vectorY)
print(vectorZ)

[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[2. 2. 3.]
[1. 2. 3.]
[2. 2. 3.]


# 矩阵拼接

## 同维度拼接
`2d -> 2d`

In [11]:
np.hstack([matrixA, matrixB])

array([[1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.],
       [7., 8., 9., 7., 8., 9.]])

In [12]:
np.vstack([matrixA, matrixB])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## 高维度拼接
`2d -> 3d`

In [15]:
np.stack([matrixA, matrixB], axis=0)

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [16]:
np.stack([matrixA, matrixB], axis=1)

array([[[1., 2., 3.],
        [1., 2., 3.]],

       [[4., 5., 6.],
        [4., 5., 6.]],

       [[7., 8., 9.],
        [7., 8., 9.]]])

# 矩阵切割

In [20]:
matrix = np.linspace(1, 16, 16).reshape([4, -1])
matrix

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [21]:
# axis的默认值为0
np.split(matrix, [1, 2])

[array([[1., 2., 3., 4.]]),
 array([[5., 6., 7., 8.]]),
 array([[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])]

In [22]:
np.split(matrix, [1, 2], axis=1)

[array([[ 1.],
        [ 5.],
        [ 9.],
        [13.]]),
 array([[ 2.],
        [ 6.],
        [10.],
        [14.]]),
 array([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.],
        [15., 16.]])]

In [24]:
np.vsplit(matrix, [1, 2])

[array([[1., 2., 3., 4.]]),
 array([[5., 6., 7., 8.]]),
 array([[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])]

In [23]:
np.hsplit(matrix, [1, 2])

[array([[ 1.],
        [ 5.],
        [ 9.],
        [13.]]),
 array([[ 2.],
        [ 6.],
        [10.],
        [14.]]),
 array([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.],
        [15., 16.]])]

# 聚合操作

In [28]:
matrix.max(axis=0)


array([13., 14., 15., 16.])

In [29]:
matrix.max(axis=1)


array([ 4.,  8., 12., 16.])

In [30]:
matrix.argmax(axis=0)


array([3, 3, 3, 3], dtype=int64)

In [31]:
matrix.argmax(axis=1)

array([3, 3, 3, 3], dtype=int64)

# 排序

In [19]:
matrix = np.array([[1, 10, 20],
                   [3, 8, 11],
                   [5, 6, 15],
                   [7, 4, 16],
                   [9, 2, 14]])
matrix

array([[ 1, 10, 20],
       [ 3,  8, 11],
       [ 5,  6, 15],
       [ 7,  4, 16],
       [ 9,  2, 14]])

In [20]:
# axis = -1, 默认是最内层进行排序
matrixSort = np.sort(matrix)
matrixSort

array([[ 1, 10, 20],
       [ 3,  8, 11],
       [ 5,  6, 15],
       [ 4,  7, 16],
       [ 2,  9, 14]])

In [21]:
# 相当于每一列单独进行排序, 移动了数据, 没有意义
matrixSort = np.sort(matrix, axis=0)
matrixSort

array([[ 1,  2, 11],
       [ 3,  4, 14],
       [ 5,  6, 15],
       [ 7,  8, 16],
       [ 9, 10, 20]])

In [24]:
# 相当于先进行数据切片, 然后传入一个切片后的矩阵, 规则同上
matrixSort = np.sort(matrix[:, [0, 2]], axis=0)
matrixSort

array([[ 1, 11],
       [ 3, 14],
       [ 5, 15],
       [ 7, 16],
       [ 9, 20]])

## 按某列进行整体排序

In [32]:
argsortIndex = np.argsort(matrix[:, 1], axis=0)
argsortIndex

array([4, 3, 2, 1, 0], dtype=int64)

In [33]:
matrix[argsortIndex]

array([[ 9,  2, 14],
       [ 7,  4, 16],
       [ 5,  6, 15],
       [ 3,  8, 11],
       [ 1, 10, 20]])